version: '2'
services:
  renren-admin:
    image: tonghe/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  renren-api:
    image: tonghe/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev